config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: [:show]
  post "/tasks/:id/toggle_status" => "tasks#toggle_status", as: :toggle_status_task

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  enum status: { pending: 'pending',  completed: 'completed' }

  validates :title, presence: true, uniqueness: true
  validates :status, presence: true, inclusion: { in: Task.statuses.keys }

  broadcasts_refreshes_to ->(tasks) { 'tasks' }

  def to_s
    title
  end

  def toggle_status!
    if pending?
      completed!
    else
      pending!
    end
  end

  def self.search(query)
    query.blank? ? all : where("title LIKE ?", "%#{sanitize_sql_like(query)}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy, :toggle_status]

  def index
    @pagy, @tasks = pagy(Task.search(params[:query]).order(:created_at))
    @task = Task.new
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      respond_to do |format|
        format.html { redirect_to tasks_url, notice: "Task was successfully created." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render  'create_error' }
      end
    end
  end

  def edit
  end

  def update
    @task.update(task_params)

    if @task.save
      respond_to do |format|
        format.html { redirect_to tasks_url, notice: "Task was successfully updated." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.turbo_stream { render 'update_error' }
      end
    end
  end

  def destroy
    @task.destroy!

    respond_to do |format|
      format.turbo_stream
    end
  end

  def toggle_status
    @task.toggle_status!

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body class="container mt-2">
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= turbo_frame_tag 'form' do %>
  <div class="border rounded shadow px-3 pb-3 pt-2">
    <h1 class="mb-2"><%= title %></h1>
    <%= simple_form_for(task) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :title %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr id="<%= dom_id(task) %>" class="<%= "table-secondary" if task.completed? %>">
  <th class="text-center">
    <%= button_to toggle_status_task_path(task), class: 'btn' do %>
      <% if task.completed? %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-square" viewBox="0 0 16 16">
          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
          <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425z"/>
        </svg>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-square" viewBox="0 0 16 16">
          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
        </svg>
      <% end %>
    <% end %>
  </th>
  <th>
    <p class="text-start mb-0 <%= "text-decoration-line-through" if task.completed? %>"><%= task.title %></p>
  </th>
  <th class="text-end">
    <% unless task.completed? %>
      <%= link_to edit_task_path(task),
                data: { turbo_frame: 'form' },
                class: 'link-success link-underline link-underline-opacity-0 me-3' do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
        </svg>
      <% end %>
    <% end %>
    <%= link_to task_path(task), data: { turbo_method: :delete }, class: 'link-danger link-underline link-underline-opacity-0' do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
      </svg>
    <% end %>
  </th>
</tr>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.append 'tasks', @task %>
<%= turbo_stream.update 'form' do %>
  <%= render partial: 'form', locals: { title: 'Add Task', task: Task.new } %>
<% end %>

app/views/tasks/create_error.turbo_stream.erb
<%= turbo_stream.update 'form' do %>
  <%= render partial: 'form', locals: { title: 'Add Task', task: @task } %>
<% end %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@task) %>

app/views/tasks/edit.html.erb
<%= render partial: 'form', locals: { title: 'Edit Task', task: @task } %>

app/views/tasks/index.html.erb
<%= turbo_stream_from 'tasks' %>
<h1 class="h1">TODO List</h1>
<div class="row">
  <div class="col-12 col-md-6">
    <%= turbo_frame_tag 'tasks-paginated' do %>
      <table class="table table-responsive table-hover align-middle">
        <thead>
          <th class="col-1">Status</th>
          <th>Task</th>
          <th class="col-1">Actions</th>
        </thead>
        <tbody id="tasks">
          <%= render @tasks %>
        </tbody>
      </table>
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    <% end %>
  </div>
  <div class="col-12 col-md-6 ps-md-5">
    <div class="border rounded shadow px-3 pb-3 pt-2 mb-2">
      <%= form_tag tasks_path,
                    method: :get,
                    class: 'form-inline',
                    data: { turbo_frame: 'tasks-paginated',
                            turbo_action: 'advance',
                            controller: 'search',
                            action: 'input->search#submit' } do %>
        <div class="row">
          <div class="col-auto">
            <%= text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search a task..' %>
          </div>
          <div class="col-auto">
            <%= submit_tag 'Search', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
    <%= render partial: 'form', locals: { title: 'Add Task', task: @task } %>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render partial: 'form', locals: { title: 'Add Task', task: @task } %>

app/views/tasks/toggle_status.turbo_stream.erb
<%= turbo_stream.replace dom_id(@task), @task %>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@task), @task %>
<%= turbo_stream.replace 'form' do %>
  <%= render partial: 'form', locals: { title: 'Add Task', task: Task.new } %>
<% end %>

app/views/tasks/update_error.turbo_stream.erb
<%= turbo_stream.update 'form' do %>
  <%= render partial: 'form', locals: { title: 'Edit Task', task: @task } %>
<% end %>